import { authService } from '../services/auth';
import { dbService } from '../services/db';
import { evolutionApi } from '../services/evolutionApi';

export const Dashboard = async () => {
    const user = authService.getCurrentUser();

    if (!user) return '';

    let metrics = {
        messages: 0,
        payments: 0,
        orders_pending: 0,
        orders_paid: 0,
        today: 0
    };

    let modulos: string[] = ['atendimento']; // Default

    if (user?.role === 'admin') {
        modulos = ['atendimento', 'venda', 'agendamento', 'disparo']; // Admin sees all
        try {
            const companies = await dbService.getAll('companies');
            companies.forEach((c: any) => {
                if (c.metrics) {
                    metrics.messages += c.metrics.totalMessages || 0;
                    metrics.payments += c.metrics.totalPayments || 0;
                }
            });
            metrics.orders_pending = 15;
            metrics.orders_paid = 1200;
        } catch (error) {
            console.error('Error fetching dashboard data:', error);
        }
    } else if (user?.companyId) {
        try {
            const companyDoc = await dbService.get('companies', user.companyId);
            const company = companyDoc as any;
            modulos = company?.modulos_ativos || ['atendimento'];

            // Count messages generated by IA
            if (modulos.includes('atendimento')) {
                const messages = await dbService.getAll('messages', {
                    field: 'empresaId',
                    operator: '==',
                    value: user.companyId
                });
                metrics.messages = messages.filter((m: any) => m.role === 'assistente').length;
            }

            // Compute total sales and orders metrics
            if (modulos.includes('venda')) {
                const orders = await dbService.getAll('pedidos', {
                    field: 'empresaId',
                    operator: '==',
                    value: user.companyId
                });
                metrics.orders_pending = orders.filter((o: any) => o.status !== 'finalizado' && o.status !== 'cancelado').length;
                metrics.orders_paid = orders.filter((o: any) => o.status === 'finalizado').length;

                let totalSales = 0;
                let ordersToday = 0;
                const today = new Date();
                today.setHours(0, 0, 0, 0);

                orders.forEach((o: any) => {
                    if (o.status === 'finalizado') {
                        totalSales += (o.value || o.total || 0);
                    }
                    const orderDate = o.criadoEm?.toDate ? o.criadoEm.toDate() : new Date(o.criadoEm || 0);
                    if (orderDate >= today) {
                        ordersToday++;
                    }
                });
                metrics.payments = totalSales;
                metrics.today = ordersToday;
            }

        } catch (error) {
            console.error('Error fetching dashboard data:', error);
        }
    }

    setTimeout(() => {
        if (user?.companyId) {
            setupStoreStatuses(user.companyId, user);
        }
    }, 100);

    return `
        <div class="page-header">
            <h2 class="page-title">Visão Geral (${user?.role === 'admin' ? 'Global' : 'Cliente'})</h2>
        </div>

        <div class="dashboard-grid">
            ${modulos.includes('atendimento') ? `
            <div class="stats-card card">
                <div class="stats-icon primary"><i style="color: #ffffff8f;" class="fa-solid fa-message"></i></div>
                <div class="stats-info">
                    <span class="label">Mensagens IA Geradas</span><br>
                    <span class="value">${metrics.messages}</span>
                </div>
            </div>
            ` : ''}

            ${modulos.includes('venda') ? `
            <div class="stats-card card">
                <div class="stats-icon success"><i style="color: #ffffff8f;" class="fa-solid fa-money-bill"></i></div>
                <div class="stats-info">
                    <span class="label">Total em Vendas</span><br>
                    <span class="value">R$ ${metrics.payments.toFixed(2)}</span>
                </div>
            </div>
            <div class="stats-card card">
                <div class="stats-icon warning"><i style="color: #ffffff8f;" class="fa-solid fa-hourglass-half"></i></div>
                <div class="stats-info">
                    <span class="label">Pedidos Pendentes</span><br>
                    <span class="value">${metrics.orders_pending}</span>
                </div>
            </div>
            <div class="stats-card card">
                <div class="stats-icon info"><i style="color: #ffffff8f;" class="fa-solid fa-box"></i></div>
                <div class="stats-info">
                    <span class="label">Pedidos Hoje</span><br>
                    <span class="value">${(metrics as any).today || 0}</span>
                </div>
            </div>
            ` : ''}
        </div>

        <div id="store-statuses-container"></div>
    `;

    async function setupStoreStatuses(companyId: string, currentUser: any) {
        const container = document.getElementById('store-statuses-container');
        if (!container) return;

        try {
            const companyDoc = await dbService.get('companies', companyId);
            const company = companyDoc as any;
            let stores = company?.stores || [];

            if (currentUser.role !== 'owner') {
                const userStoreIds = currentUser.storeIds || (currentUser.storeId ? [currentUser.storeId] : []);
                stores = stores.filter((s: any) => userStoreIds.includes(s.id));
            }

            if (stores.length === 0) {
                container.innerHTML = `
                    <div class="card" style="margin-top: 1.5rem; background: rgba(239, 68, 68, 0.05); border: 1px solid rgba(239, 68, 68, 0.2);">
                        <h3 style="color: var(--danger);"><i class="fa-solid fa-triangle-exclamation"></i> Sistema Inoperante</h3>
                        <p style="color: var(--text-muted); font-size: 0.9rem;">Nenhuma loja encontrada ou associada a este usuário. O sistema não pode operar.</p>
                    </div>
                `;
                return;
            }

            let html = '';

            for (const store of stores) {
                let statusHtml = '';
                let isOnline = false;

                if (!store.instancia_id || !store.active) {
                    statusHtml = `
                        <div style="background: rgba(239, 68, 68, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--danger); margin-bottom: 1rem;">
                            <p style="margin: 0; font-weight: 600; color: var(--danger);"><i class="fa-solid fa-circle-xmark"></i> Loja Inoperante</p>
                            <p style="margin: 0.25rem 0 0 0; font-size: 0.85rem; color: var(--text-muted);">A loja está inativa ou não possui instância vinculada.</p>
                        </div>
                    `;
                } else {
                    const instDoc = await dbService.get('instancias', store.instancia_id);
                    const instanceName = (instDoc as any)?.nome;
                    if (instanceName) {
                        try {
                            const status = await evolutionApi.getInstanceStatus(instanceName);
                            if (status.connected) {
                                isOnline = true;
                                statusHtml = `
                                    <div style="background: rgba(34, 197, 94, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid #22c55e; margin-bottom: 1rem;">
                                        <p style="margin: 0; font-weight: 600; color: #22c55e;"><i class="fa-solid fa-circle-check"></i> Instância Conectada</p>
                                        <p style="margin: 0.25rem 0 0 0; font-size: 0.85rem; color: var(--text-muted);">A IA e o WhatsApp estão online (Instância: ${instanceName}).</p>
                                    </div>
                                `;
                            } else {
                                const qrData = await evolutionApi.getQRCode(instanceName);
                                statusHtml = `
                                    <div style="background: rgba(239, 68, 68, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--danger); margin-bottom: 1rem;">
                                        <p style="margin: 0; font-weight: 600; color: var(--danger);"><i class="fa-solid fa-triangle-exclamation"></i> Instância Desconectada</p>
                                        <p style="margin: 0.25rem 0 0.5rem 0; font-size: 0.85rem; color: var(--text-muted);">Instância: ${instanceName}. Escaneie o QR Code.</p>
                                        ${qrData?.base64 ? `<img src="${qrData.base64}" alt="QR" style="width:150px;height:150px;display:block;margin:0 auto;border-radius:8px;">` : '<p style="font-size:0.8rem;text-align:center;">Sem QR Code</p>'}
                                    </div>
                                `;
                            }
                        } catch (e) {
                            statusHtml = `<p style="color:var(--danger);font-size:0.85rem;">Erro ao verificar instância (${instanceName}).</p>`;
                        }
                    } else {
                        statusHtml = `<p style="color:var(--danger);font-size:0.85rem;">Instância vinculada não encontrada no banco de dados.</p>`;
                    }
                }

                const freteAtivo = store.frete_ativo !== false; // default to true if undefined

                html += `
                    <div class="card" style="margin-top: 1.5rem; border: 1px solid ${isOnline ? 'rgba(34,197,94,0.3)' : 'rgba(239,68,68,0.3)'};">
                        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem;">
                            <div>
                                <h3 style="margin-bottom: 0.25rem;"><i class="fa-solid fa-store"></i> ${store.name}</h3>
                                <div style="display:flex; gap: 0.5rem;">
                                    <span class="badge ${(store.active && store.instancia_id) ? 'success' : 'danger'}">${(store.active && store.instancia_id) ? 'Operante' : 'Inoperante'}</span>
                                    <span class="badge ${isOnline ? 'success' : 'warning'}">${isOnline ? 'WhatsApp Online' : 'WhatsApp Offline'}</span>
                                    <span class="badge ${freteAtivo ? 'success' : 'warning'}">${freteAtivo ? 'Frete Ativo' : 'Retirada Apenas'}</span>
                                </div>
                            </div>
                        </div>
                        ${statusHtml}
                    </div>
                `;
            }

            container.innerHTML = html;

            // Toggle frete removed from dashboard

        } catch (error) {
            console.error('Error setting up Store statuses:', error);
            container.innerHTML = `
                <div class="card" style="margin-top: 1.5rem; background: var(--surface-hover);">
                    <p style="color: var(--danger);">Erro ao carregar os status integrados.</p>
                </div>
            `;
        }
    }
};
